spring.application.name=backend
server.port=8080

# For future Redis/MySQL configs
# spring.datasource.url=jdbc:mysql://mysql:3306/weather_db
# spring.datasource.username=root
# spring.datasource.password=root
# spring.data.redis.host=redis
# spring.data.redis.port=6379
